properties(
    [
        [
            $class: 'BuildDiscarderProperty',
            strategy: [$class: 'LogRotator', numToKeepStr: '10']
        ],
        pipelineTriggers([cron('H/5 * * * *')]),
    ]
)

try{
    node() {

        stage('build'){
             openshiftBuild(buildConfig: 'dotnet-core-app-web-bc', showBuildLogs: 'true')
        }

        stage('deploy') {
            openshiftDeploy(deploymentConfig: 'dotnet-core-app-web-dc')
        }
    }
} catch (Exception e) {
    throw e;
}