properties(
    [
        [
            $class: 'BuildDiscarderProperty',
            strategy: [$class: 'LogRotator', numToKeepStr: '10']
        ],
        pipelineTriggers([cron('H/5 * * * *')]),
    ]
)

try{
    node('any') {

        stage('build'){
             openshiftBuild(buildConfig: '${NAMEPFX}-web-bc', showBuildLogs: 'true')
        }

        stage('deploy') {
            openshiftDeploy(deploymentConfig: '${NAMEPFX}-web-dc')
        }
    }
} catch (Exception e) {
    echo "send error mail to andriy.gnennyy@globallogic.com"
    mail subject: "Build failed with ${e.message}", to: "andriy.gnennyy@globallogic.com", body: "Job failed: ${env.BUILD_URL} \n\n${e.stackTrace}"
    throw e;
}