properties(
    [
        [
            $class: 'BuildDiscarderProperty',
            strategy: [$class: 'LogRotator', numToKeepStr: '10']
        ],
        //pipelineTriggers([cron('H/5 * * * *')]),
    ]
)

def changesOnPath(){
	return false
}


try{
    node {
		if (!changesOnPath()){
			currentBuild.result = 'SUCCESS'
			return
		}

        stage('build'){
             openshiftBuild(buildConfig: 'dotnet-core-app-web-bc', showBuildLogs: 'true')			 
        }

        stage('deploy') {
            openshiftDeploy(deploymentConfig: 'dotnet-core-app-web-dc')
        }
    }
} catch (Exception e) {
    throw e;
}